### ISSUE TITLE
Health Check Best Practice

### ISSUE THREAD

**Issue by sammerry** [gaul/s3proxy#256]
I really like this project but I'm not sure what the health check best practice is. Is there a /ping or /health check endpoint? Any simple way to get a 2xx response?

**Comment by gaul** [comment]
AWS does not offer an API like this but you can list all buckets (`GET /`) and check a known bucket (`HEAD /bucket`) cheaply.  A hypothetical `GET /?info` endpoint could allow users to interrogate the recommended multipart sizes and number of keys per bucket, especially since S3Proxy supports different backends with different values.  I hesitate to add a S3Proxy-specific API but maybe a proof-of-concept pull request combined with some Ceph and Minio vendor evangelism could move this forward?

**Comment by cuttingedge1109** [comment]
Health check endpoint without authentication is desirable for s3proxy itself.
