### ISSUE TITLE
Add JUnit rule for easy stubbing in JUnit tests

### ISSUE THREAD

**Issue by ddcprg** [gaul/s3proxy#261]
We've created a JUnit Rule which we've like to contribute to this project. 

The rule is meant to make it easy to stub a S3 endpoint in a JUnit test and is based on S3Proxy and we think it would be useful to other developer out there. The following snapshot of code shows how we've been using this rule in our tests:

```
  public @Rule S3ProxyRule s3Proxy = S3ProxyRule
      .builder()
      .withPort(s3ProxyPort)
      .withCredentials(AWS_ACCESS_KEY, AWS_SECRET_KEY)
      .ignoreUnknownHeaders()
      .build();
```

Then

```
  private AmazonS3 s3Client;

  @Before
  public void init() throws Exception {
    s3Client = AmazonS3ClientBuilder
        .standard()
        .withCredentials(
            new AWSStaticCredentialsProvider(new BasicAWSCredentials(s3Proxy.getAccessKey(), s3Proxy.getSecretKey())))
        .withEndpointConfiguration(new EndpointConfiguration(s3Proxy.getProxyUrl(), Regions.US_EAST_1.getName()))
        .build();
    s3Client.createBucket("my-test-bucket");
  }

```

I was going to open a PR with the code but I prefer to discuss where in the project this should leave. Perhaps convert the project to make it multi-module? Please advise

**Comment by gaul** [comment]
Can we host this `@Rule` in the existing S3Proxy repository and jar?

**Comment by ddcprg** [comment]
Hi @gaul Thanks for the prompt response. We could add it to the existing repo with the current layout but the rule has a compile time dependency with JUnit. I've noticed that your POM has this dep with _test_ scope.

**Comment by gaul** [comment]
Ideally S3Proxy should not impose a JUnit compile-time dependency on all its users.  Unfortunately JUnit does not offer a separate annotations jar like Error Prone.  I wonder if you can fake it `@Rule` by redefining it?  I believe Error Prone allowed this for some nullness annotation.  Maybe worth raising an upstream issue with JUnit?

Another possibility is that S3Proxy could publish its test jar.  Perhaps this could more cleanly separate some non-test uses of S3Proxy from the test uses.  Can you investigate this?

If there is not a workaround, I prefer to host the JUnit rule outside the S3Proxy repository.  I can link the README and wiki to your downstream rule library and will watch the repository for support questions.  If the rule code is really trivial, we can just add some example code which users can cut and paste.

**Comment by massdosage** [comment]
One option would be to make the dependency on junit "provided" - this would still mean a compile time, but not necessarily a runtime dependency. This way only users of the rule would need to depend on Junit, which they would need to do anyway in order to actually use it with JUnit. Not perfect but maybe acceptable?

The problem with publishing the test jar is that this would then also contain all the unit test classes which one wouldn't really want downstream.

The best solution I can think of to avoid the compile time dependency on Junit would be to split s3proxy into separate modules with a "core" of some kind containing what the existing code and a "rule" module with the rule. Or could one create some kind of "test" module which contains the rule and some other stuff which is only test related?

The rule code is just one class of less than 200 lines of code. We could make this its own project, it just feels like overkill for one class.

**Comment by gaul** [comment]
Provided scope for junit sounds like exactly what we need and compile-time dependency seems OK.  Can you submit a pull request?  jclouds just released 2.1.0 so I hope to run a new S3Proxy release soon which could include this.

**Comment by massdosage** [comment]
OK, I will discuss with @ddcprg (we work together) and try get a PR ready for you asap. Thanks!

**Comment by gaul** [comment]
@massdosage Can you add a blurb about JUnit to the wiki:

https://github.com/gaul/s3proxy/wiki/Using-S3Proxy-in-Java-projects

**Comment by massdosage** [comment]
Sure, I've added a blurb and usage example. Looking forward to 1.6.0!
