### ISSUE TITLE
filesystem backend cannot complete large multipart uploads

### ISSUE THREAD

**Issue by gaul** [gaul/s3proxy#292]
S3Proxy via jclouds filesystem implements multipart upload by first creating the parts as files then reading the parts sequentially and writing them to the destination file.  This incurs 3x IO and I observed S3 clients timing out when writing a 25 GB object.  Instead, I wonder if it could write to a single temporary file at the correct offsets then just rename to the destination file?

**Comment by kahing** [comment]
aws s3 works around the timeout issue by emitting whitespaces in response periodically: https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html

your idea of writing to the correct offset won't work because parts can be uploaded out of order, and the API doesn't give you information about missing offsets

**Comment by gaul** [comment]
Agree that writing to a single file won't work since clients don't use fixed size parts.  However S3Proxy should periodically emit newlines during complete as you suggested.

**Comment by timuralp** [comment]
For what it's worth, Swift also allows clients to opt into a similar whitespace behavior (https://docs.openstack.org/swift/latest/overview_large_objects.html) and exposes the same through its s3api.
