### ISSUE TITLE
multiple client identities

### ISSUE THREAD

**Issue by kortemik** [gaul/s3proxy#356]
I would like to create backend for authenticating multiple users which then would be proxied forward as a one user. For this approach I did some research and found out that BlobStoreLocator is quite tightly tied with the identities to provide multibackend support for a single instance of the s3proxy. 

Requirements for such a authentication/authorization component are that it needs to access the request and can return users from a source such as ldap. Initially I would create a simple implementation that works just like the current static one. However due to the tight coupling of BlobStoreLocator and the identity this is not that straight forward so therefore please advice how this could be done in such a way that it will be usable/mergeable in order to benefit others as well.

**Comment by gaul** [comment]
`BlobStoreLocator` allows mapping a given identity to a (credential, BlobStore) pair.  Multiple `--properties` flags allow adding several different static configurations as you have discovered.  But `BlobStoreLocator` could be any dynamic implementation if you programmatically override it via `setBlobStoreLocator`.  Does this address your use case?  Otherwise I am happy to accept PRs to improve this although the current configuration mechanism is limiting as @timuralp discovered in the currently open sharded blobstore PR.

**Comment by kortemik** [comment]
thank you, i'll investigate on the possibility to use a custom locator. it seems on the first hand to offer enough information for our use case.
