### ISSUE TITLE
Docker Hub latest tag is 3 months ago

### ISSUE THREAD

**Issue by gaul** [gaul/s3proxy#408]
The latest tag looks strange:

https://hub.docker.com/r/andrewgaul/s3proxy/tags

@ansman maybe related to your changed in #382?

**Comment by ansman** [comment]
You can see in my PR (https://github.com/gaul/s3proxy/pull/391/files#r749858733) that the `latest` tag will only be updated if you push a git tag. This maps to the best practices with Docker where `latest` refer to the latest released version as opposed to the latest pushed commit.

**Comment by gaul** [comment]
This makes sense.  Sorry I missed this earlier.

**Comment by gaul** [comment]
I pushed a new tag but latest is still not updated.  Any pointers?

**Comment by ansman** [comment]
@gaul You can see why here: https://github.com/gaul/s3proxy/actions/runs/2085063419

It's because the tag name isn't parsable (it was ` s3proxy-2.0.0`). If you instead tag it with `2.0.0` then it should work as expected.

**Comment by gaul** [comment]
Changing the tags sounds like a headache.  Why can't the script just ignore the `s3proxy-` prefix?

**Comment by ansman** [comment]
I used https://github.com/docker/metadata-action to handle the tagging. They seem to expect a [semver](https://semver.org) compatible tag name which doesn't allow for prefixes like that.

You could switch the tagging to be `raw` (which just uses the tag name as is) but then you'd lose some of the benefit.

There currently seems to be no way to ignore the prefix so you're stuck with replacing that action, changing how tagging happens or drop the prefix from the tag name. I would recommend the last option, mostly because I think tags should be semver compatible.

**Comment by gaul** [comment]
Pushed manually via:

```
sudo docker build . -t andrewgaul/s3proxy:latest
sudo docker push andrewgaul/s3proxy
```

However this only pushes linux/amd64 and not linux/arm64.  I don't have time to investigate this but will happily merge improvements that do not require changing the tag scheme.
