### ISSUE TITLE
S3 proxy without authentication (sent by the client) ?

### ISSUE THREAD

**Issue by scebll** [gaul/s3proxy#741]
Hi, first of all thanks for this project, it looks great and I see that the community is very supportive - that's always appreciated.

I'm doing a personal PoC using s3proxy to make requests against an AWS S3 bucket with a very particular casuistry: instead of s3proxy storing the credentials, send them as if they were part of a request - the goal is to use s3proxy as middleware to “inspect” the requests.

Reviewing the documentation I could see that s3proxy does not have as functionality the ACL / etc. but there is no mention of authentication (or I have not been able to see it).

Is there any concrete way to, for example if I send a request to s3proxy (configuring as endpoint the s3proxy host) it sends the request to AWS with the signature that already comes from the request (for example using Cyberduck or s3cmd)?
 
I have tried to raise the container on minimal, but I always get a Forbidden. Instead with the specific AWS configuration I've tried with agnostic S3:

```docker run --rm --publish 8180:80 --env S3PROXY_AUTHORIZATION=aws-v2-or-v4 --env JCLOUDS_PROVIDER=s3 --env JCLOUDS_ENDPOINT=https://s3.eu-south-2.amazonaws.com --env LOG_LEVEL=debug andrewgaul/s3proxy```

And (as example) - I've been using the following `s3cmd` configuration:

```[default]
access_key = <theOriginalAccessKeyfromAWS>
secret_key = <theOriginalSecretKeyfromAWS>
host_base = <ip>:8180
host_bucket = <ip>:8180
```

Thank you for your help!

**Comment by gaul** [comment]
This isn't possible due to the way S3Proxy works.  You can think about this as:

original S3 HTTP request → cross-cloud Java code → new S3 HTTP request

I think you need something that preserves the HTTP request.  Perhaps the confusingly similarly-named [S3-Proxy](https://oxyno-zeta.github.io/s3-proxy/) might work for your use case?

But if your issue is that you you don't want S3Proxy to store the credentials, I think S3 supports a variety of token or credentialess authentication when running on EC2.  I'm not sure if the underlying Apache jclouds provider exposes this today, although it does for Azure #728.  So it might be worth looking at that if you understand Java.
